# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FIT_Studkurator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FIT_Studkurator
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
end
